
export type User = {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  provider?: string;
};

export type AuthState = {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
};

export type Transaction = {
  id: string; // Typically generated by the backend
  type: boolean; // true for income, false for expense
  category: string;
  amount: number;
  // Date from backend is typically a full ISO string (e.g., "2023-10-26T10:00:00Z").
  // For forms or NewTransactionData, it's often handled as "YYYY-MM-DD".
  date: string; 
  description: string;
  // userId?: string; // Optional: if transactions are user-specific and API requires it in payload
};

// Represents data for creating a new transaction, date as YYYY-MM-DD from form
export type NewTransactionData = Omit<Transaction, 'id'>;

export type Category = {
  id: string;
  name: string;
  color: string;
  icon: string;
};

export type ThemeMode = 'light' | 'dark';

export type ChartData = {
  name: string;
  value: number;
  color: string;
};

export type TimeFrame = 'week' | 'month' | 'year' | 'custom';
